package Quandoo;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class QuandooHomepageSuiteTest {

  private WebDriver driver;

  @Before
  public void setUp() {
      System.setProperty("webdriver.chrome.driver", "src\\main\\resources\\Windows\\chromedriver.exe");
      driver = new ChromeDriver();
  }

  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void findRestaurantsInBerlin() {
    driver.get("https://www.quandoo.de/en");
    driver.manage().window().setSize(new Dimension(1829, 1038));
    driver.findElement(By.xpath("(//input[@name=\'destination\'])[2]")).sendKeys("Berlin");
    driver.findElement(By.xpath("//*[@data-qa=\"button-search-find-hero\"]")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@data-qa=\'listing-header\']"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.xpath("//h1")).getText(), is("Restaurants in Berlin"));
    driver.close();
  }
  @Test
  public void findBarThatIsInBerlinButNotOnTheWebsite() {
    driver.get("https://www.quandoo.de/en");
    driver.manage().window().setSize(new Dimension(1829, 1038));
    driver.findElement(By.xpath("(//input[@name=\'dining\'])[2]")).sendKeys("The Hat");
    driver.findElement(By.xpath("//*[@data-qa=\"button-search-find-hero\"]")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@data-qa=\'listing-header\']"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.xpath("//h1")).getText(), is("Restaurants in Berlin"));
    assertThat(driver.findElement(By.xpath("//span[@data-qa=\"search-text\"]")).getText(), is("\\\"The Hat\\\""));
    assertThat(driver.findElement(By.xpath("//div[@data-qa=\'results-count\']")).getText(), is("200+\\\\n results"));
  }
  @Test
  public void findRestaurantsBurgerClickRestaurant() {
    driver.get("https://www.quandoo.de/en");
    driver.manage().window().setSize(new Dimension(1829, 1038));
    driver.findElement(By.xpath("(//input[@name=\'dining\'])[2]")).sendKeys("burger");
    driver.findElement(By.xpath("(//form[@id=\'searchForm\']/div/div/div/div[2]/li[3]/div/span[2])[3]")).click();
    assertThat(driver.findElement(By.xpath("//h1")).getText(), is("BurgerAMT"));
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@data-qa=\'book-a-table-button\']/button"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".reservation-tab-btn"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void findRestaurantsInNearMe() {
    driver.get("https://www.quandoo.de/en");
    driver.manage().window().setSize(new Dimension(1829, 1038));
    driver.findElement(By.xpath("(//button[@data-qa=\'search-bar-near-me-icon\'])[2]")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@data-qa=\'listing-header\']"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.xpath("//h1")).getText(), is("Restaurants Near Me"));
    assertThat(driver.findElement(By.xpath("//div[@data-qa=\'listing-header\']/div/div/span")).getText(), is("Enable location services to see restaurants near you."));
  }
  @Test
  public void findRestaurantsPizzaClickCuisines() {
    driver.get("https://www.quandoo.de/en");
    driver.manage().window().setSize(new Dimension(1829, 1038));
    driver.findElement(By.xpath("(//input[@name=\'dining\'])[2]")).sendKeys("Pizza");
    driver.findElement(By.xpath("(//form[@id=\'searchForm\']/div/div/div/div[2]/li[4]/div/span[2])[2]")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@data-qa=\'listing-header\']"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.xpath("//h1")).getText(), is("Pizza in Berlin"));
  }
  @Test
  public void findRestaurantsPizzaType() {
    driver.get("https://www.quandoo.de/en");
    driver.manage().window().setSize(new Dimension(1829, 1038));
    driver.findElement(By.xpath("(//input[@name=\'dining\'])[2]")).sendKeys("Pizza");
    driver.findElement(By.xpath("//*[@data-qa=\"button-search-find-hero\"]")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@data-qa=\'listing-header\']"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.xpath("//h1")).getText(), is("Restaurants in Berlin"));
    {
      List<WebElement> elements = driver.findElements(By.xpath("//span[@data-qa=\"search-text\"]"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.xpath("//span[@data-qa=\"search-text\"]")).getText(), is("\\\"Pizza\\\""));
  }
  @Test
  public void findSpecificRestaurantClick() {
    driver.get("https://www.quandoo.de/en");
    driver.manage().window().setSize(new Dimension(1829, 1038));
    driver.findElement(By.xpath("(//input[@name=\'dining\'])[2]")).sendKeys("Wartesaal");
    driver.findElement(By.cssSelector(".cIiuCR .sc-14zpp84-0")).click();
    assertThat(driver.findElement(By.xpath("//h1")).getText(), is("Wartesaal"));
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@data-qa=\'book-a-table-button\']/button"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".reservation-tab-btn"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void findSpecificRestaurantEnter() {
    driver.get("https://www.quandoo.de/en");
    driver.manage().window().setSize(new Dimension(1829, 1038));
    driver.findElement(By.xpath("(//input[@name=\'dining\'])[2]")).sendKeys("Wartesaal");
    driver.findElement(By.cssSelector(".cIiuCR .sc-14zpp84-0")).sendKeys(Keys.ENTER);
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@data-qa=\'listing-header\']"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.xpath("//h1")).getText(), is("Restaurants in Berlin"));
    assertThat(driver.findElement(By.xpath("//span[@data-qa=\"search-text\"]")).getText(), is("\\\"Wartesaal\\\""));
    assertThat(driver.findElement(By.xpath("//div[@data-qa=\'results-count\']")).getText(), is("300+\\\\n results"));
    {
      List<WebElement> elements = driver.findElements(By.linkText("Wartesaal"));
      assert(elements.size() > 0);
    }
  }
}
